import type { Metadata } from "next";
import { Geist, Geist_Mono, Playwrite_AU_QLD } from "next/font/google";
import "./globals.css";
import ClientSessionWrapper from "@/components/sessionProvider";
import { TanstackProvider } from "@/components/tanstackProvider";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playwrite = Playwrite_AU_QLD({
  variable: "--font-playwrite",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playwrite.variable} antialiased`}
      >
        <ClientSessionWrapper>
          <TanstackProvider>
            {children}
            <ToastContainer
              position="bottom-right"
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick={false}
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="dark"
            />
          </TanstackProvider>
        </ClientSessionWrapper>
      </body>
    </html>
  );
}
